ical_urls = ["https://calendar.google.com/calendar/ical/en.usa%23holiday%40group.v.calendar.google.com/public/basic.ics"]
rss_feeds = ["http://feeds.bbci.co.uk/news/world/rss.xml#"]
update_interval = "60"
api_key = ""
location = "Stuttgart, DE"
week_starts_on = "Monday"
calibration_hours = [0,12,18]
display_type = "colour" #colour, black_and_white
language = "en"
units = "metric"
hours = "24"
top_section = "Weather"
middle_section = "Calendar "#"Agenda"#"Calendar"
bottom_section = "RSS"
