name: Inkycal testing

on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: run Inkycal tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Clone repo
      run: |
        git clone --single-branch https://github.com/aceinnolab/Inkycal
    - name: Creating virtual environment
      run: |
        cd Inkycal
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install wheel
        pip install -e ./
    - name: generate docs
      run: |
        cd docsource
        make html
    - name: Deploy Docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ._build/html
    - name: Setup test environment and run tests
      env:
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        SAMPLE_ICAL_URL: ${{ secrets.SAMPLE_ICAL_URL }}
        TEST_ICAL_URL: ${{ secrets.TEST_ICAL_URL }}
        TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
      run: |
        cd ..
        echo "$PWD"
        cd inkycal/tests
        wget https://raw.githubusercontent.com/aceinnolab/Inkycal/assets/tests/settings.json
        for f in *.py; do python3 "$f"; done
