name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Clone repo
      run: |
        git clone --branch feature/venv --single-branch https://github.com/aceisace/Inkycal

    - name: Creating virtual evvironment
      run: |
        cd Inkycal
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        
    - name: Install dependencies
      run: |
        echo "$PWD"
        pip install wheel
        pip install -e ./
        # cd inkycal/modules && ls -al
        
    - name: Run tests
      env:
        OPENWEATHERMAP_API_KEY: secrets.OPENWEATHERMAP_API_KEY
        
      run: |
        echo "$PWD"
        # cd ..
        cd tests
        wget https://raw.githubusercontent.com/aceisace/Inkycal/assets/tests/settings.json
        # sed -i 's/"api_key":.*/"api_key": "${{secrets.OPENWEATHERMAP_API_KEY}}",/' settings.json
        for f in *.py; do python3 "$f"; done
