name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Clone repo
      run: |
        git clone --branch feature/venv --single-branch https://github.com/aceisace/Inkycal

    - name: Creating virtual evvironment
      run: |
        cd Inkycal
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        
    - name: Install dependencies
      run: |
        echo "$PWD"
        pip install wheel
        pip install -e ./

    - name: Setup test environment
      run: |
        cd inkycal/modules && ls -al
        cd ..
        cd tests
        echo "${{ secrets.ENV_FILE }}" > .env
        wget https://raw.githubusercontent.com/aceisace/Inkycal/assets/tests/settings.json

    - name: Run unittests
      run: |
        for f in *.py; do python3 "$f"; done
